name: Publish_to_Docker_Hub

on:
  # Ручной запуск
  workflow_dispatch:

jobs:
  #build_and_test:
   # name: Maven
    #uses: sanchev/HelloWorld/.github/workflows/maven.yml@a5c82f67df77f7c13c26a5f4d72ee3a163064a79
        
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    #needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2 
      #- name: Restore target directory from cache
       # uses: actions/cache@v2
        #with:
         # path: ./target
          #key: ${{ runner.os }}-target-${{ hashFiles('**/target/*.jar') }}
          #restore-keys: |
           # ${{ runner.os }}-target-
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: |
          echo ${{ secrets.DOCKER_REPO }}
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $VERSION
          #echo ${{secrets.DOCKER_REPO }} | sed 's/./& /g'
          #docker build -t ${{secrets.DOCKER_REPO }}:$VERSION .
      #- name: Publish Docker image
       # run: docker push ${{ secrets.DOCKER_REPO }}
