name: Build_and_Test_with_Maven

on:
  # Ручной запуск
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Save target directory to cache
        uses: actions/cache@v2
        with:
          path: ./target
          key: ${{ runner.os }}-target-${{ hashFiles('**/target/*.jar') }}
          restore-keys: |
            ${{ runner.os }}-target-
      - name: Build and test project with Maven
        run: mvn -B package --file pom.xml
